Support custom region
Sceptre/sceptre-ssm-resolver pull request #7
Opened 2021-04-13 21:48 UTC by ykhalyavin

In some cases you want to store a secret in a single region and then pass it to all you stacks in other regions.

My use case -- the same token for Kinesis across 17 regions is stored in a single region (to be keep it maintainable) and passed as a parameter to all stack in all 17 regions

2021-04-13 22:18 UTC, ykhalyavin commented
There's a thread how to fix cryptography build... I'm guessing the original image might need to be updated @zaro0508  could you please have a look?

https://github.com/pyca/cryptography/issues/5771

2021-04-19 20:04 UTC, zaro0508 requested changes
LGTM in general, just request for an additional test.

2021-04-19 20:04 UTC, zaro0508 commented on tests/test_ssm.py
> +    def test_resolve_obj_arg_region_override(self, mock_get_parameter_value):
can you please add an additional test to check when user does not provide a region, similar to the existing `test_resolve_obj_arg_no_profile` test?

2021-04-23 17:18 UTC, ykhalyavin commented on tests/test_ssm.py
> +    def test_resolve_obj_arg_region_override(self, mock_get_parameter_value):
Isn't it already covered by the existing tests:

- test_resolve_str_arg_no_param_name
- test_resolve_obj_arg_no_profile
- test_resolve_obj_arg_profile_override 

tests above cover all other usecases -- string, object with name, object with name and profile

Please let me know if I missed something

2021-04-23 18:40 UTC, zaro0508 requested changes

2021-04-23 18:40 UTC, zaro0508 commented on tests/test_ssm.py
> +    def test_resolve_obj_arg_region_override(self, mock_get_parameter_value):
there is no test for passing in a `name`, and `profile` but not a `region`

2021-04-23 18:40 UTC, zaro0508 commented on tests/test_ssm.py
> +                "region": custom_region,
i would like to see a test where the name and profile are provided but the region is not.

2021-04-30 17:34 UTC, ykhalyavin commented on tests/test_ssm.py
> +                "region": custom_region,
I would love to add the test, but I think there's some misunderstanding (maybe on my side).

Please have a look at the **test_resolve_obj_arg_profile_override**, we pass {"name": "/dev/DbPassword", "profile": "new_profile"} as a parameter (no region included), and we do anticipate that the _get_parameter_value will be called with "region" parameter afterwards, since it's a mandatory one (stacks's region by default).

![image](https://user-images.githubusercontent.com/477081/116732110-444a7280-a9b0-11eb-98f3-2daf49bb03c6.png)

2021-05-03 22:52 UTC, zaro0508 commented on tests/test_ssm.py
> +                "region": custom_region,
ok, sorry I misunderstood what you mean.  I thought when you said `Isn't it already covered by the existing tests`, i thought you were referring to unaltered tests that currently exist in the repo.  Looking at it again I see that you modified an existing test to check what I was asking for.

2021-05-03 22:53 UTC, zaro0508 approved these changes

2021-05-04 04:30 UTC, merged